-- GENERACION DEL DDL

DROP DATABASE IF EXISTS proyecto_mktdigital ; -- Optech

CREATE DATABASE proyecto_mktdigital;

USE proyecto_mktdigital;

-- Tabla CLIENTE
CREATE TABLE CLIENTE (
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) DEFAULT 'USUARIO_UNKNOW',
    TELEFONO VARCHAR(20) NOT NULL,
    MAIL VARCHAR(100) UNIQUE NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL
);

-- Tabla EMPLEADO
CREATE TABLE EMPLEADO (
    IDEMPLEADO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    CARGO VARCHAR (100),
    TELEFONO VARCHAR(20),
    MAIL VARCHAR(100)
);


-- Tabla TIPOSERVICIO
CREATE TABLE TIPOSERVICIO (
    IDTIPOSERVICIO INT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(100),
    DESCRIPCION VARCHAR (100),
    COMENTARIO VARCHAR (1000)
);


-- Tabla SERVICIO
CREATE TABLE SERVICIO (
    IDSERVICIO INT PRIMARY KEY AUTO_INCREMENT,
    IDTIPOSERVICIO INT,
    DESCRIPCION VARCHAR (100),
	FECHA DATETIME
);

-- Tabla PLATAFORMA_MKT

CREATE TABLE PLATAFORMA_MKT (
    IDPLATAFORMA INT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(100),
    DESCRIPCION VARCHAR (100),
    TIPO_SATURACION BOOLEAN
);

-- Tabla ASIGNACION_PRESUPUESTO

CREATE TABLE ASIGNACION_PRESUPUESTO (
    IDASIGNACION INT PRIMARY KEY AUTO_INCREMENT,
	IDCLIENTE INT,
    IDPLATAFORMA INT,
	FECHA DATETIME,
    MONTO INT
);

-- Tabla VENTA

CREATE TABLE VENTA (
    IDVENTA INT PRIMARY KEY AUTO_INCREMENT,
	IDCLIENTE INT,
    IDSERVICIO INT,
	IDEMPLEADO INT,
    FECHA DATETIME,
    COMENTARIO VARCHAR(1000)
);

-- Tabla COBRO

CREATE TABLE COBRO (
    IDCOBRO INT PRIMARY KEY AUTO_INCREMENT,
    IDVENTA INT,
	IDCLIENTE INT,
	IDEMPLEADO INT,
    FECHA DATETIME,
    COMENTARIO VARCHAR(1000)
);

-- Tabla PERFORMANCE_PLATAFORMAS

CREATE TABLE PERFORMANCE_PLATAFORMAS (
    IDPERFORMANCE_PLATAFORMAS INT PRIMARY KEY AUTO_INCREMENT,
    IDPLATAFORMA INT,
	METRICA INT,
    FECHA DATETIME
);

-- Tabla FORMA_COBRO

CREATE TABLE FORMA_COBRO (
    IDFORMA_COBRO INT PRIMARY KEY AUTO_INCREMENT,
	IDCOBRO INT,
    COMENTARIO VARCHAR(1000)   
);

-- Tabla HISTORIAL_COBRO

CREATE TABLE HISTORIAL_COBRO (
    IDHISTORIAL_COBRO INT PRIMARY KEY AUTO_INCREMENT,
    IDFORMA_COBRO INT,
	IDCOBRO INT,
    IDEMPLEADO INT,
    COMENTARIO VARCHAR(1000)   
);

-- FOREIGN KEYS DEFINITION

    
-- SERVICIO
ALTER TABLE SERVICIO
    ADD CONSTRAINT FK_TIPO_SERVICIO
    FOREIGN KEY (IDTIPOSERVICIO) REFERENCES TIPOSERVICIO(IDTIPOSERVICIO);
    
-- ASIGNACION_PRESUPUESTO

ALTER TABLE ASIGNACION_PRESUPUESTO
    ADD CONSTRAINT FK_ASIGNACION_PRESUPUESTO_CLIENTE
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE ASIGNACION_PRESUPUESTO
    ADD CONSTRAINT FK_ASIGNACION_PRESUPUESTO_PLATAFORMA
    FOREIGN KEY (IDPLATAFORMA) REFERENCES PLATAFORMA_MKT(IDPLATAFORMA);

-- VENTA

ALTER TABLE VENTA
    ADD CONSTRAINT FK_VENTA_CLIENTE
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE VENTA
    ADD CONSTRAINT FK_VENTA_EMPLEADO
    FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO);

ALTER TABLE VENTA
    ADD CONSTRAINT FK_VENTA_SERVICIO
    FOREIGN KEY (IDSERVICIO) REFERENCES SERVICIO(IDSERVICIO);
    
-- COBRO

ALTER TABLE COBRO
    ADD CONSTRAINT FK_COBRO_VENTA
    FOREIGN KEY (IDVENTA) REFERENCES VENTA(IDVENTA);

ALTER TABLE COBRO
    ADD CONSTRAINT FK_COBRO_EMPLEADO
    FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO);
    
-- PERFORMANCE_PLATAFORMAS

ALTER TABLE PERFORMANCE_PLATAFORMAS
    ADD CONSTRAINT FK_PERFORMANCE_PLATAFORMAS_PLATAFORMA_MKT
    FOREIGN KEY (IDPLATAFORMA) REFERENCES PLATAFORMA_MKT(IDPLATAFORMA);
    
-- HISTORIAL_COBRO

ALTER TABLE HISTORIAL_COBRO
    ADD CONSTRAINT FK_HISTORIAL_COBRO_COBRO
    FOREIGN KEY (IDCOBRO) REFERENCES COBRO(IDCOBRO);
    
ALTER TABLE HISTORIAL_COBRO
    ADD CONSTRAINT FK_HISTORIAL_COBRO_FORMA_COBRO
    FOREIGN KEY (IDFORMA_COBRO) REFERENCES FORMA_COBRO(IDFORMA_COBRO);
